use serde::{Deserialize, Deserializer, Serialize};
use std::path::PathBuf;

/// A detected programming language in the project.
///
/// Serializes/deserializes as a plain string (e.g. `"Python"`, `"Rust"`).
/// Unknown language strings map to `Other(s)`.
#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub enum Language {
    Rust,
    Python,
    TypeScript,
    JavaScript,
    Go,
    Java,
    CSharp,
    Cpp,
    C,
    Ruby,
    Swift,
    Kotlin,
    Other(String),
}

impl<'de> Deserialize<'de> for Language {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        Ok(match s.as_str() {
            "Rust" => Language::Rust,
            "Python" => Language::Python,
            "TypeScript" => Language::TypeScript,
            "JavaScript" => Language::JavaScript,
            "Go" => Language::Go,
            "Java" => Language::Java,
            "CSharp" => Language::CSharp,
            "Cpp" => Language::Cpp,
            "C" => Language::C,
            "Ruby" => Language::Ruby,
            "Swift" => Language::Swift,
            "Kotlin" => Language::Kotlin,
            other => Language::Other(other.to_string()),
        })
    }
}

/// A detected framework or major dependency.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectedFramework {
    pub name: String,
    pub version: Option<String>,
    pub category: FrameworkCategory,
}

/// Category of a framework/dependency.
///
/// Deserializes case-insensitively from a plain string; unknown values map to `Other`.
#[derive(Debug, Clone, Serialize)]
pub enum FrameworkCategory {
    Web,
    MachineLearning,
    DataProcessing,
    Database,
    Testing,
    Build,
    Cli,
    Hardware,
    Other,
}

impl<'de> Deserialize<'de> for FrameworkCategory {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        Ok(match s.as_str() {
            "Web" | "web" => FrameworkCategory::Web,
            "MachineLearning" | "Machine Learning" | "ML" => FrameworkCategory::MachineLearning,
            "DataProcessing" | "Data Processing" => FrameworkCategory::DataProcessing,
            "Database" | "database" => FrameworkCategory::Database,
            "Testing" | "testing" => FrameworkCategory::Testing,
            "Build" | "build" => FrameworkCategory::Build,
            "Cli" | "CLI" | "cli" => FrameworkCategory::Cli,
            "Hardware" | "hardware" => FrameworkCategory::Hardware,
            _ => FrameworkCategory::Other,
        })
    }
}

/// Represents a point in the project where AI techniques could be integrated.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IntegrationPoint {
    pub file_path: PathBuf,
    pub description: String,
    pub suggested_approach: String,
    pub complexity: IntegrationComplexity,
}

/// Integration complexity level.
///
/// Deserializes case-insensitively; unknown values default to `Medium`.
#[derive(Debug, Clone, Serialize)]
pub enum IntegrationComplexity {
    Low,
    Medium,
    High,
}

impl<'de> Deserialize<'de> for IntegrationComplexity {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        Ok(match s.as_str() {
            "Low" | "low" => IntegrationComplexity::Low,
            "Medium" | "medium" => IntegrationComplexity::Medium,
            "High" | "high" => IntegrationComplexity::High,
            _ => IntegrationComplexity::Medium,
        })
    }
}

/// The complete profile of a user's project, generated by project analysis.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectProfile {
    /// Root path to the project.
    pub path: PathBuf,

    /// User-provided description of what they want to add.
    pub user_request: String,

    /// AI-generated summary of the project's purpose and architecture.
    pub summary: String,

    /// Primary language(s) detected.
    pub languages: Vec<Language>,

    /// Frameworks and major dependencies detected.
    pub frameworks: Vec<DetectedFramework>,

    /// File count and structure summary.
    pub file_count: usize,

    /// Key files (entry points, configs, etc.).
    pub key_files: Vec<PathBuf>,

    /// Identified integration points for AI techniques.
    pub integration_points: Vec<IntegrationPoint>,

    /// Raw file tree (truncated to reasonable depth).
    pub file_tree: String,
}
